import "./styles/style.css";
import { layout } from "./layout";
import { footer } from "./footer";
import { navBar } from "./navBar";
import { header } from "./header";
import { newPopup } from "./newPopup";
import { TodoManager } from "./TodoManager";
import { NotesManager } from "./NotesManager";
import { ProjectManager } from "./ProjectManager";
import { displayHome } from "./displayHome";

layout();
footer();
header();
newPopup();
TodoManager.updateArray();
NotesManager.updateNotes();
ProjectManager.updateProjects();
navBar();
displayHome();
